Test/Test/Controllers/GetSwiftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Device.Location;
using Test.Models.GetSwiftTest;
using Test.ViewModels;
using Test.Services;
using Test.Infrastructure;

namespace Test.Controllers
{
    public class GetSwiftController : Controller
    {
        public ActionResult Test() 
        {
            var service = new GetSwiftService();
            IEnumerable<Drone> dronesInput = service.GetDrones();
            IEnumerable<Package> packagesInput = service.GetPackages();

            var drones = dronesInput.Select(p => new
                {
                    droneId = p.droneId,
                    delayTimeSpan = p.location.TimeSpanCalculator(p.packages.FirstOrDefault())
                }) 
                .OrderBy(k => k.delayTimeSpan)
                .ToList();

            var nowUnixSeconds = TimeHelper.UnixNow();

            var packages = packagesInput
                .Select(p => new 
                {
                   packageId = p.packageId,
                   minTimeSpan = p.destination.TimeSpanCalculator(),
                   maxTimeSpan = p.deadline - nowUnixSeconds,                  
                });

           //wrong deadline, not able to delivery on time
            var rejectedPackages = packages
                .Where(p => p.maxTimeSpan < p.minTimeSpan)
                .Select(k => k.packageId)
                .OrderBy(k => k)
                .ToList();

            //Sorted by min gap between left time and calculated delivery time
            var approvedPackages = packages
                .Where(p => !rejectedPackages.Any(pp => pp == p.packageId))
                .OrderBy(k => k.maxTimeSpan - k.minTimeSpan)
                .ToList();

            List<AssignedPair> assignedPackages = new List<AssignedPair>();
            List<int> notAssignedPackages = new List<int>();

            foreach (var p in approvedPackages)
            {
                if (drones.Count() == 0) {
                    List<int> lastPackages = approvedPackages
                         .SkipWhile(k => k.packageId == p.packageId)
                         .Select(k => k.packageId)
                         .ToList();
                    notAssignedPackages.AddRange(lastPackages);
                    break;
                }

                var drone = drones.FirstOrDefault(k => p.maxTimeSpan >= k.delayTimeSpan + p.minTimeSpan);
                if (drone == null)
                {
                    notAssignedPackages.Add(p.packageId);
                }
                else 
                {
                    assignedPackages.Add(new AssignedPair()
                    {
                        droneId = drone.droneId, 
                        packageId = p.packageId,
                        delivery = (nowUnixSeconds + p.minTimeSpan + drone.delayTimeSpan).UnixDateToString(),
                        deadline = (nowUnixSeconds + p.maxTimeSpan).UnixDateToString(),
                        needTime = (drone.delayTimeSpan + p.minTimeSpan).SecondsToString()
                    });

                    drones.Remove(drone);                   
                }           
            }

            var vm = new GetSwiftTestViewModel(){
                Drones = dronesInput,
                Packages = packagesInput,
                AssignedPackages = assignedPackages,
                RejectedPackages = rejectedPackages,
                NotAssignedPackages = notAssignedPackages.OrderBy(p => p)
            };
            return View(vm);
        }

    }
}

Test/Test/Controllers/GoldenPondController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Test.Models.GoldenPond;
using Test.ViewModels;

namespace Test.Controllers
{
    public class GoldenPondController : Controller
    {        
        public ActionResult Test()
        {
            string stringCommands1 = "PFPFPFPFF";                                            
            DuckState stateStart1 = new DuckState() { X = 1, Y = 2, Orientation = Orientation.N };
            DuckState stateEnd1 = new DuckState(stateStart1);
            stateEnd1.FollowCommands(stringCommands1);

            string stringCommands2 = "FFSFFSFSSF";
            DuckState stateStart2 = new DuckState() { X = 3, Y = 3, Orientation = Orientation.E };
            DuckState stateEnd2 = new DuckState(stateStart2);
            stateEnd2.FollowCommands(stringCommands2);

            IEnumerable<GoldenPondViewModel> vm = new List<GoldenPondViewModel>() {

                new GoldenPondViewModel() {                  
                    StartState = stateStart1,
                    EndState = stateEnd1,
                    Commands = stringCommands1
                },
                new GoldenPondViewModel() {
                    StartState = stateStart2,
                    EndState = stateEnd2,
                    Commands = stringCommands2
                },
            };

            return View(vm);
        }
    }
}

Test/Test/Controllers/MessagesDBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Test.ViewModels;
using Test.Repositories.MessagesDB;
using Test.Models.MessagesDB;

namespace Test.Controllers
{
    public class MessagesDBController : Controller
    {
        private IMessagesDBRepository<Person, int> _repo;

        public MessagesDBController(IMessagesDBRepository<Person, int> repo)
       {
           _repo = repo;
       }

        public ActionResult TestEF()
        {
             var domains = _repo.GetDomains();
             var emailAddressesWithPersonNames = _repo.GetEmailAddressesWithPersonNames();
             var emailsCountForDomains = _repo.GetEmailsCountForDomains();

             var vm = new MessagesDBViewModel()
             {
                 Title = "EF",
                 Domains = domains,
                 EmailAddressesWithPersonNames = emailAddressesWithPersonNames,
                 EmailsCountForDomains = emailsCountForDomains,
             };
            return View("Test", vm);
        }

        public ActionResult TestSQL()
        {
            var domains = _repo.GetDomainsSQL();
            var emailAddressesWithPersonNames = _repo.GetEmailAddressesWithPersonNamesSQL();
            var emailsCountForDomains = _repo.GetEmailsCountForDomainsSQL();

            var vm = new MessagesDBViewModel()
            {
                Title = "SQL",
                Domains = domains,
                EmailAddressesWithPersonNames = emailAddressesWithPersonNames,
                EmailsCountForDomains = emailsCountForDomains,
            };
            return View("Test", vm);
        }
    }
}

Test/Test/Controllers/TestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Test.Controllers
{
    public class TestsController : Controller
    {
       
        public ActionResult Index()
        {
            return View();
        }
    }
}

Test/Test/Controllers/TinyUrlController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using Test.Models.TinyUrl;
using Test.Repositories.TinyUrl;
using Test.ViewModels;
using Test.Services;
using System.Net.Http;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace Test.Controllers
{
    public class TinyUrlController : Controller
    {
        public const int ConstItemsPerPage = 10;        
        private ITinyUrlRepository<UrlMap, int> _repo;


        public TinyUrlController(ITinyUrlRepository<UrlMap, int> repo)
       {
           _repo = repo;
       }


        public ActionResult RedirectToFullUrl(string id)
        {
            var tinyUrl = id;
            if (tinyUrl.Count() > UrlMap.MaxDigitNumber)
                return View("RedirectError",
                            (object)("Wrong alias. Alias max length can't be more than " +  UrlMap.MaxDigitNumber));
               

            var cacheService = new CacheService();
            var urlMap = cacheService.GetOrSet("TinyUrl-"+ tinyUrl, 
                                () =>_repo.GetUrlMapById(UrlMap.GetIdByTinyUrl(tinyUrl)));
            if (urlMap != null)
            {
                return Redirect(urlMap.LongUrl);
            }
            else
            {
                return View("RedirectError",
                            (object)("No Long Url for alias '" + tinyUrl + "' was not found. Not able to redirect."));
            }
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult DeleteUrlMap(int id)
        {
            var cacheService = new CacheService();
            string tinyUrl = UrlMap.GetTinyUrlById(id);
            var urlMap = cacheService.Remove<UrlMap>("TinyUrl-" + tinyUrl);
            var result = _repo.DeleteUrlMap(id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Home()
        {
            ViewBag.Host = Request.Url.Scheme + "://" + Request.Url.Authority + "/";
            return View(new UrlMap());
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult MakeTinyUrl(UrlMap urlMap)
        {           
           urlMap.LongUrl = UrlMap.MakeUrlWithProtocol(urlMap.LongUrl);
           var result = IsUrlExists(urlMap.LongUrl);
       
            if (result)
            {
                urlMap = _repo.AddUrlMap(urlMap);
            }
            else {
                urlMap.Id = -3;
            }
            return Json( urlMap, JsonRequestBehavior.AllowGet);
       }

      
        [NonAction]
        public bool IsUrlExists(string FullUrl)
        {
            string url = UrlMap.MakeUrlWithProtocol(FullUrl);
            bool result;
            try
            {
                HttpWebRequest request = WebRequest.Create(url) as HttpWebRequest;
                request.Method = "HEAD";
                HttpWebResponse response = request.GetResponse() as HttpWebResponse;
                result = (response.StatusCode == HttpStatusCode.OK);
               
            }
            catch
            {
                result = false;
            }
            return result;
        }

        public ActionResult Index(int id = 1, int itemsPerPage = ConstItemsPerPage)
        {         
            var pageNumber = id;
            var urlMaps = _repo.GetUrlMaps(pageNumber, itemsPerPage);
            var urlMapsCount = _repo.GetUrlMapsCount();

            var vm = new UrlMapsViewModel(){
                    Host = Request.Url.Scheme + "://" + Request.Url.Authority + "/",
                    PageNumber = pageNumber,
                    PagesNumber = (int)Math.Ceiling((double)urlMapsCount / itemsPerPage),
                    ItemsPerPage = itemsPerPage,
                    UrlMaps = urlMaps,
                    UrlMapsCount = urlMapsCount
                };

            if (Request.IsAjaxRequest())
            {
                return Json(new {gridInfo = vm }, JsonRequestBehavior.AllowGet);
            }
           
            else return View(vm);
        }
    }
}

Test/Test/Views/Tests/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutTests.cshtml";
}

@section MainContent{

    <div class="row  hidden-sm hidden-xs" style="margin-top:10px;">
        <div class="col-md-3">
            <h3><b>Test</b></h3>
        </div>
        <div class="col-md-9">
            <h3><b>Test menu</b></h3>
        </div>
    </div>
    <hr/>

    <div class="row">
        <div class="col-md-3">
            <h5><b>Tiny URL</b></h5>
        </div>
        <div class="col-md-9">
            <div class="navbar navbar-inverse">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="#" class="navbar-brand nav navbar-nav">
                        <span class="glyphicon glyphicon-cog"></span>
                    </a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Home", "TinyUrl")</li>
                        <li>@Html.ActionLink("Admin", "Index", "TinyUrl")</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <hr />


    <div class="row">
        <div class="col-md-3">
            <h5><b>Messages DB & Golden Pond</b></h5>
        </div>
        <div class="col-md-9">
            <div class="navbar navbar-inverse">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="#" class="navbar-brand nav navbar-nav">
                        <span class="glyphicon glyphicon-cog"></span>
                    </a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Messages DB - EF", "TestEF", "MessagesDB")</li>
                        <li>@Html.ActionLink("Messages DB - SQL", "TestSQL", "MessagesDB")</li>
                        <li>@Html.ActionLink("Golden Pond", "Test", "GoldenPond")</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <hr />

    <div class="row">
        <div class="col-md-3">
            <h5><b>GetSwift</b></h5>
        </div>
        <div class="col-md-9">
            <div class="navbar navbar-inverse">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="#" class="navbar-brand nav navbar-nav">
                        <span class="glyphicon glyphicon-cog"></span>
                    </a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("GetSwift Test", "Test", "GetSwift")</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <hr />
   
}

@section scripts{
<script>
$(function() {
    $('.navbar-toggle1').on('click', function () {
        {
            $(this).trigger( "click" );
        }
    });
});
</script>
}